### ISSUE TITLE
Handle New task workflow changes(Status site)

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-status#234]
**Details :-**  https://github.com/Real-Dev-Squad/website-backend/issues/460

**Tasks :-**

- [x] On the availability panel render only tasks that are available, not unAssigned(handle it before migration such that both AVAILABLE and unAssigned works)
- [x] When the task is assigned to a member from the availability panel make the status of the task as ASSIGNED and startedOn should be computed and endsOn should be 14 days by default
- [x]  **active → IN_PROGRESS, unAssigned → AVAILABLE, completed → VERIFIED** handle both scenarios such that **active**  behaves the same as **IN_PROGRESS** (Same for other changes)
