### ISSUE TITLE
TODO list for issues page task management modal

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/website-status#963]
- [x] Add a close icon, scroll listener and keyboard key listener to close the the modal 
- [x] Reuse the existing update task request RTK query by making necessary changes
- [x] Finalise task assignment / update flow
- [x] Fix default description value
